### PR TITLE
Increase access to the main functions

### PR DESCRIPTION
**Pull request by janus**
This PR would increase ones access to the daemon from client and it made hostaddress mandatory.

### CODE REVIEW

**Review by vyzo — COMMENTED** [review]
Thank you, this is a welcome change; there is an issue however.

The problem with mandatory host address is that we can't start the daemon without listening to any address, which is useful functionality.
Also, the "use random port" part is lost in translation.

Can you add a check for host-address being `#f` and then omit the argument if that's the case?
This would fix the issues.
1. Start the daemon with a random listen address, maybe we just don't care
2. Star the daemon with `-noListenAddrs` which would start it without listening anywhere.

**Comment by vyzo** [comment]
We can also make it an optional argument as well.

**Comment by janus** [comment]
> Thank you, this is a welcome change; there is an issue however.
> 
> The problem with mandatory host address is that we can't start the daemon without listening to any address, which is useful functionality.
> Also, the "use random port" part is lost in translation.
> 
> Can you add a check for host-address being `#f` and then omit the argument if that's the case?
> This would fix the issues.
> 
>     1. Start the daemon with a random listen address, maybe we just don't care
> 
>     2. Star the daemon with `-noListenAddrs` which would start it without listening anywhere.

@vyzo Thanks for your review. Please go through the code once again.

**Review by vyzo — APPROVED** [review]

**Comment by vyzo** [comment]
thank you!

**Comment by janus** [comment]
> thank you!

Thanks so much!

**Pull request merged**
